services:
  # Service 1: The Web Server
  web:
    build: .                  # Build from current folder
    image: my-webapp-v1       # Tag the image with this name
    ports:
      - "8080:5000"           # Map host port 8080 to container 5000
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    volumes:
      - web_data:/app/data

    # NEW FEATURE: Auto-Update
    # enabled: true (without URL) means "Watch local files for changes"
    # If you edit app.py, LockBox will detect the hash change and rebuild/restart.
    depends_on:
      - redis-db

    auto-update:
      enabled: true

  # Service 2: The Database
  redis-db:
    image: redis-custom
    build: ./db  # Points to the folder containing the redis app.lbox
    volumes:
      - redis_data:/data
